on: pull_request

jobs:
  comment_preview_deploy_pr:
    runs-on: ubuntu-latest
    name: Comment on a PR with the URL to the preview deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview deployment available at https://pr${{ github.event.number }}-blog.namisunami.com
permissions:
  pull-requests: write
